### ISSUE TITLE
Building MDT

### ISSUE THREAD

**Issue by arash-n** [robbert-harms/MDT#23]
Dear Robbert,

I was wondering if it is possible to install/build MDT without sudo privileges on a CentOS 6.10 cluster. 

Best,
Arash

**Comment by robbert-harms** [comment]
Hi Arash,

That should be possible as long as OpenCL as a driver platform is available on the cluster. From that point on it is only a matter of installing the Python packages which can be done using ``pip`` and installing to the users home folder.

Does this answer your question?

Best,

Robbert

**Comment by arash-n** [comment]
Yes. Worked pretty well.

-Arash
