### ISSUE TITLE
MDT kurtosis vs DKE

### ISSUE THREAD

**Issue by droediger** [robbert-harms/MDT#26]
The same subject was run through HCP (4.0.1) Preprocessing followed by both MDT's kurtosis fitting and [DKE](https://www.nitrc.org/projects/dke) kurtosis estimation.

Looking at the axial kurtosis maps (I assume "KurtosisTensor.AK.nii.gz" is axial kurtosis), the MDT output has _much_ higher values across the white matter than the corresponding DKE output. Why are the results this different?

MDT AK:
![mdt_ak](https://user-images.githubusercontent.com/47993467/86142637-03947b00-bab9-11ea-9bf5-1d657298052c.png)

DKE AK:
![dke_KAX](https://user-images.githubusercontent.com/47993467/86142719-1d35c280-bab9-11ea-9f29-32a359b5952f.png)

The mean kurtosis (MK) maps look similar across MDT and DKE but with a more dark voxels (indicating failed model fitting?) in the MDT output. Is this due to some smoothing or robust fitting that is included in DKE but not MDT?

MDT MK:
![mdt_mk](https://user-images.githubusercontent.com/47993467/86143510-207d7e00-baba-11ea-95b3-7419f2a26a96.png)

DKE MK:
![dke_mk](https://user-images.githubusercontent.com/47993467/86143522-25423200-baba-11ea-87cb-b8f947983b26.png)

 I ran MDT like so:

     mdt-model-fit \
          Kurtosis \
          /input_dir/${sub}/${ses}/T1w/Diffusion/data.nii.gz \
          /input_dir/${sub}/${ses}/T1w/Diffusion/bvecs.prtcl \
          /input_dir/${sub}/${ses}/T1w/Diffusion/nodif_brain_mask.nii.gz \
          --gradient-deviations /input_dir/${sub}/${ses}/T1w/Diffusion/grad_dev.nii.gz

**Comment by droediger** [comment]
PS looking at the ReturnCodes maps, the whole brain is "1" with some speckles of "6" throughout... what am I doing wrong here?

**Comment by robbert-harms** [comment]
Hi droediger,

These differences are to be expected. MDT uses non-linear optimization methods for all model fitting, similar to [1], except MDT uses a offset-gaussian noise model. Non-linear model fitting may not necessarily be the optimal method for Kurtosis modelling. With a Gaussian noise model the Kurtosis can be estimated using linear optimization methods, which has certain advantages in robustness of fit. With an offset-gaussian or Rician noise model, the standard linear optimization techniques do not work anymore and the next best technique is non-linear model optimization, as done in MDT.

About your other question. A return code of 1 indicates successful optimization, a return code of 6 indicates that it could not readily converge and that the search was terminated at some point in time.

Best wishes,

Robbert

References:
[1]: Constrained Maximum Likelihood Estimation of the Diffusion Kurtosis Tensor Using a Rician Noise Model, 
Jelle Veraart, Wim Van Hecke, Jan Sijbers, https://pubmed.ncbi.nlm.nih.gov/21416503/
