### ISSUE TITLE
very low MD values after fitting Tensor Model

### ISSUE THREAD

**Issue by SanRut** [robbert-harms/MDT#27]
Dear Harm,

I fitted the tensor model on my DWI data and the resulting MD values are rather low, in the order of 1e-9. I wanted to ask whether these low values are normal. In your NeuroImage (2017) paper, I see that the diffusion is expressed in seconds per meter, should I also interpret the MD values at this scale?

Thank you, best wishes,

Sanne

**Comment by robbert-harms** [comment]
Hi Sanne,

Yes, MDT uses SE units (seconds, meters, etc.) when representing the data. As such, the Tensor diffusivities, as well as the FA and MD are represented in m^2/s, while the typical units are in mm^2/s. You can simply rescale the FA by 1e6 to get the typical range of units (mm^2/s).

Best wishes,

Robbert

**Comment by SanRut** [comment]
Hi Harm,

Thanks so much for your quick and helpful reply.

Best wishes, Sanne
