### ISSUE TITLE
installation on ubuntu 20.04

### ISSUE THREAD

**Issue by SherS2** [robbert-harms/MDT#28]
I am getting the following installation error   

$ sudo apt-get install python3-mdt
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 python3-mdt : Depends: python3-mot but it is not installable
E: Unable to correct problems, you have held broken packages.

**Comment by robbert-harms** [comment]
Hi SherS2,

Thank you for reporting this issue. I will look into, but due to personal circumstances I can't guarantee when that will be. 

In the meantime, you could also install MDT using pip, i.e. ``pip install mdt``.

Best wishes,

Robbert
