### ISSUE TITLE
Access tu more GPU nodes

### ISSUE THREAD

**Issue by StefaniaOliviero** [robbert-harms/MDT#35]
Hi all,
I need to execute a Levember Marquardt fit on an acquisition with more than 1000 spatial directions and I verified that this calls for more than 64 GB of VRAM - GPU. I would like to know if MDT could work on more nodes of GPUs.

**Comment by robbert-harms** [comment]
Hi Stefania,

Unfortunately also that won't work. You hit a roadblock in the current design of MDT. I have some plans for changing this whenever OpenCL 3.0 gets more widely supported, but for now I am afraid this won't work. I would love to have it as much as you do.

Best,

Robbert

**Comment by StefaniaOliviero** [comment]
Thanks so much Robbert for your answer... Maybe I could fix the issue with a Virtual Machine on Google, I HOPE.
Thanks again and have a good job.
Cheers

Ottieni Outlook per Android<https://aka.ms/ghei36>

________________________________

**Comment by robbert-harms** [comment]
At your service. If you need anything else you know where to find me.
