### ISSUE TITLE
Threading when using CPUs

### ISSUE THREAD

**Issue by celstark** [robbert-harms/MDT#36]
We've been using MDT on several workstations with GPUs in them happily.  But, we now are shifting over to a cluster setup that does not have GPUs but does have nodes with 144 CPU cores.

```
Singularity> mdt-list-devices -l
Device 0:
===========================================================================
<pyopencl.Platform 'Portable Computing Language' at 0x7f43d8000020>
===========================================================================
extensions: cl_khr_icd
name: Portable Computing Language
profile: FULL_PROFILE
vendor: The pocl project
version: OpenCL 1.2 pocl 1.1 None+Asserts, LLVM 6.0.0, SPIR, SLEEF, DISTRO, POCL_DEBUG

---------------------------------------------------------------------------
<pyopencl.Device 'pthread-Intel(R) Xeon(R) CPU E7-8895 v3 @ 2.60GHz' on 'Portable Computing Language' at 0x2e20aa0>
---------------------------------------------------------------------------
...
max compute units: 144
```
Yet, when running here, I sit with ~1 CPU fully loaded and that's about it when running mdt-model-fit.  I'm polling the CPU usage and the highest I've seen is 113%.  My fans aren't even getting a workout.

I'd thought that with OpenCL it would fork this out to all the CPU cores I have and yet I'm seemingly running only single-threaded.  Any ideas?

Craig

**Comment by robbert-harms** [comment]
Hi Craig,

I see you are using the POCL library. So far I haven't been very successful with POCL. Some kernels compile, some don't. I think what you are seeing is that POCL is still compiling one of the compute kernels. This compilation is single threaded. Only after that is done the actual computation begins which is always multi-threaded.

It has been a while since I last checked in on the POCL project. Maybe newer versions have improved compilation.

For now, could you try installing the Intel OpenCL CPU drivers? This worked well for me in the past and they should work with MDT.

Best,

Robbert

**Comment by celstark** [comment]
So... in searching around trying to find how to get the Intel OpenCL CPU drivers on Ubuntu 18.04 I found [this thread of yours on the Intel forums](https://community.intel.com/t5/OpenCL-for-CPU/Ubuntu-18-04-OpenCL-driver/td-p/1127141).  I also found [this PPA](https://launchpad.net/~intel-opencl/+archive/ubuntu/intel-opencl/+packages) and have installed the .deb files libigdgmm11_21.1.2-1~ppa1~bionic1_amd64.deb, libze-intel-gpu_21.18.19737-1~ppa1~bionic1_amd64.deb, intel-opencl-icd_21.18.19737-1~ppa1~bionic1_amd64.deb, libigc_1.0.7152-1~ppa1~bionic1_amd64.deb, libze-loader_1.2.3-1~ppa1~bionic1_amd64.deb) manually but still no joy.

Have you got another good source for getting these in on bionic?  It seems that may be your environment, so any deb files you may have there would be great as would any pointers on what I'm looking for.  I'm clearly not an OpenCL guy ;) but at least not only am I a neuroscientist trying to run this, I'm also the one who sets up and runs the cluster.

Thanks,

Craig

**Comment by celstark** [comment]
OK, took some digging, but I got the OpenCL Intel driver in place and I managed to capture it using 14400% of CPU -- so all 144 cores.  15.8s of real time and 11m32s of user time.  Dang that's some nice parallel work!

**Comment by robbert-harms** [comment]
Hi Craig,

I am happy to hear that you solved it. Could you share your end solution? This might help others in a similar situation.

Best,

Robbert

**Comment by celstark** [comment]
I just put it up on GitHub -- https://github.com/StarkLabUCI/MDT_Singularity_OpenCL

Craig
