### ISSUE TITLE
Difference between CHARMED models

### ISSUE THREAD

**Issue by StefaniaOliviero** [robbert-harms/MDT#37]
Hi all, I would like to know the difference between the models CHARMED-r1, CHARMED-r2, and CHARMED-r3. Unfortunately, I don't understand where to find the description of the model parameters. 
Thanks a lot for the support.

Regards
Stefania Oliviero

**Comment by robbert-harms** [comment]
Hi Stefania,

The difference between CHARMED-r1, CHARMED-r2, and CHARMED-r3 is in the number of restricted model compartments used. That is CHARMED_r1 uses one hindered compartment and one restricted compartment, _r2 has one hindered and 2 restricted, _r3 uses three restricted compartments. A similar naming scheme is found in the BallStick models.

The idea is that you would you use the *_r1 models for voxels where you expect only one dominant fiber direction (e.g. corpus callosum), *_r2 models for voxels with two crossing/bending/kissing fiber directions (just outside the CC) and *_r3 for voxels with three directions (eg. the centrum semiovale).

Best,

Robbert
