### ISSUE TITLE
Confusing error message "Double operator in model listing."

### ISSUE THREAD

**Issue by lukeje** [robbert-harms/MDT#38]
Using the same model name twice raises an error here:
https://github.com/robbert-harms/MDT/blob/79012e86a28f612d632fa299ffc4a120993abc3a/mdt/model_building/trees.py#L110
but the message is ambiguous (I first thought it related to single vs. double floating point).
Perhaps "Duplicate operator in model listing." would be more unambiguous?

**Comment by robbert-harms** [comment]
Hi Luke, 

That is a good suggestion. 

I changed it and I will put it in the next minor release.

Thanks,

Robbert
