### ISSUE TITLE
Open CL errors

### ISSUE THREAD

**Issue by mwagshul** [robbert-harms/MDT#39]
Robbert,

Thank you so much for making this code freely available, it's a great package and was working fine until a few months ago.
Now I am unable to run it without getting the following errors. This is being run on Linux, OS is CentOS, and it's attempting to run the NODDI module. The errors would seem to be related to OpenCL, but not sure what changed on the system that would have generated this error, which I was not getting previously (it is possible that IT had in the interim updated python or some other module which MDT is using, but haven't been able to figure that out.  Thanks for any advice on how to fix this.

Best,

Mark

Traceback (most recent call last):
  File "/public/apps/anaconda/3-5.2.0/envs/mdt/bin/mdt-model-fit", line 6, in <module>
    from mdt.cli_scripts.mdt_model_fit import ModelFit
  File "/public/apps/anaconda/3-5.2.0/envs/mdt/lib/python3.7/site-packages/mdt/__init__.py", line 8, in <module>
    import mot
  File "/public/apps/anaconda/3-5.2.0/envs/mdt/lib/python3.7/site-packages/mot/__init__.py", line 3, in <module>
    from .optimize import minimize, get_minimizer_options
  File "/public/apps/anaconda/3-5.2.0/envs/mdt/lib/python3.7/site-packages/mot/optimize/__init__.py", line 1, in <module>
    from mot.lib.cl_function import SimpleCLFunction
  File "/public/apps/anaconda/3-5.2.0/envs/mdt/lib/python3.7/site-packages/mot/lib/cl_function.py", line 6, in <module>
    from mot.configuration import CLRuntimeInfo
  File "/public/apps/anaconda/3-5.2.0/envs/mdt/lib/python3.7/site-packages/mot/configuration.py", line 20, in <module>
    from .lib.cl_environments import CLEnvironmentFactory
  File "/public/apps/anaconda/3-5.2.0/envs/mdt/lib/python3.7/site-packages/mot/lib/cl_environments.py", line 180, in <module>
    _cl_environment_cache = _initialize_cl_environment_cache()
  File "/public/apps/anaconda/3-5.2.0/envs/mdt/lib/python3.7/site-packages/mot/lib/cl_environments.py", line 160, in _initialize_cl_environment_cache
    for platform in cl.get_platforms():
pyopencl._cl.LogicError: clGetPlatformIDs failed: PLATFORM_NOT_FOUND_KHR

**Comment by robbert-harms** [comment]
hi Mark, 

Thank you for the compliments. Hopefully we can fix this for you.

The message PLATFORM_NOT_FOUND_KHR is indeed a typical OpenCL related error. Could you try running the command line utility "clinfo" and see if that works and finds any OpenCL devices?

My guess is that the nvidia/amd drivers were updated and that the OpenCL drivers are now either missing or incorrectly linked to the graphic driver. Probably clinfo will crash as well and then it's a job for the IT department.

Let me know how it goes,

Best,

Robbert

**Comment by mwagshul** [comment]
Thanks Robbert, unfortunately my system doesn't recognize that command so is this a deeper problem? Again, odd because I know the package worked for a long time. Thanks again for the help with getting this running.

Best,

Mark

**Comment by robbert-harms** [comment]
Not at all. clinfo is a standalone utility which you probably haven't installed yet. Probably you need something like "yum install clinfo".

**Comment by mwagshul** [comment]
Hmm, that would require admin privileges, which would take a few days for
them to get around to. Is there a version which I can install locally (e.g.
pip install)?

**Comment by robbert-harms** [comment]
Unfortunately not. You could try opening a Python shell and typing:
```python
import pyopencl as cl
cl.get_platforms()
```

it will probably crash because the CL drivers are not initialized correctly. Having an independent tool (clinfo) verify this would add some extra information.

**Comment by mwagshul** [comment]
But no surprise here, get the same error as before (I think this is the
function that you're code was failing on):

pyopencl._cl.LogicError: clGetPlatformIDs failed: PLATFORM_NOT_FOUND_KHR

**Comment by robbert-harms** [comment]
Yes, but the point is that it is not an MDT or MOT problem (my packages), but a problem with OpenCL. I am aware that that doesn't solve your issue, but it makes it clear that it technically not an MDT or MOT issue.

My advice would be to ask your IT department if they can verify your OpenCL installation.

**Comment by mwagshul** [comment]
Yes, thanks for the help. I'm in touch with them and they're working on it.

Best,

Mark

**Comment by robbert-harms** [comment]
Did it work? If so, then we can close this issue. :)

**Comment by mwagshul** [comment]
No, sorry. Been busy with other things. Very strange behavior - my system
admin can run all of the programs just fine, even when he logs into my
account. But I can't run anything, and neither can a few other users who
I've checked with.

The only thing I can think of, which I've asked him to check, is that he
can directly ssh into the GPU node. I can't do that. I need to qrsh in,
which I have had some problems with in other applications (Parallel
processing in Matlab specifically). But still not sure why this would make
a difference.

Thanks for asking, and if you have any ideas, let me know.

Best,

Mark

**Comment by mwagshul** [comment]
Robbert,

I seem to have "fixed" the problem, but the processing seems to be very,
very slow. Instead of using the globally installed version of MDT, I
installed it locally and using that version, it at least doesn't fail right
away as it did before when using the globally installed MDT version. But
now it seems to be stuck on the "We will use the optimizer Powell with
default settings." step for a long time (my past experience was that it
only took a few minutes to complete (dataset is 246 volumes). I am running
this on a 8-processor NVIDIA GPU.

Thoughts? Is there a way to run the processing in "verbose" mode to see
what it's doing?

Thanks,

Mark

**Comment by robbert-harms** [comment]
Hi Mark,

Happy to hear it works, sad to hear it is slow. Can you provide me with the rest of the log output? Could you additionally run mdt-list-devices and tell me the output? I have the idea that it is using a different device for the computations and not your nvidia GPU.

Unfortunately MDT does not have an additional verbose mode. The log file is what I use for debugging purposes.

Best,

Robbert

**Comment by mwagshul** [comment]
Well, I think I've solved the problem. It seems to have to do with the
memory request when I qrsh into the GPU node. If I don't request a
particular block of memory, I get those errors relating to OpenCL, but when
I request 30G (it seems to use up to ~ 20G peak), then it runs fine in ~ 5
minutes. Mystery solved, although the errors we were getting were odd and
not obviously related to the memory requested. It's also odd that this was
working a few months ago without the memory request.

Thanks for all your help, I think we're back in business!

Mark

**Comment by robbert-harms** [comment]
Hi Mark, happy that it works! Good luck with your science. 

Best, Robbert
